### ISSUE TITLE
Cross-origin Ajax calls in IE8 and IE9

### ISSUE THREAD

**Issue by amireynoso** [mercadolibre/tiny.js#25]
We came across an "Access denied" error in IE9 when implementing the **ui-navigation_modeless_box** component (which depends on tiny.js) in Search (and also in MyML). The error log pointed to the Ajax .open() method. 

After researching what could be happening, we figured it could be a cross-origin matter. We believe adding a fallback in tiny's .ajax() method could solve this, as suggested in [this topic](http://stackoverflow.com/questions/3362474/jquery-ajax-fails-in-ie-on-cross-domain-calls).

**Comment by atma** [comment]
What version of tiny.js? Does it work with `credentials: "include"` configuration parameter of [ajax settings](https://github.com/mercadolibre/tiny.js#tinyajaxurl-settings)?

**Comment by amireynoso** [comment]
The component uses [tiny.js v0.1.2](https://github.com/mercadolibre/ui-navigation_modeless_box/blob/master/package.json#L36). I've just checked and the *credentials* parameter is set, [see here](https://github.com/mercadolibre/ui-navigation_modeless_box/blob/master/src/scripts/Bookmarks.js#L37). 

The error can be reproduced by navigating to My Account (being logged in) > Questions > and then opening the Bookmarks popup, using IE9.

**Comment by atma** [comment]
Thanks @amireynoso for the good explanation, finally I got it :smiley: Will release the fix soon.
BTW, tiny.js is in npm repository so you can just use `"tiny.js": "0.1.2"` instead of `"tiny.js": "mercadolibre/tiny.js#v0.1.2"`.

**Comment by amireynoso** [comment]
Awesome! Thank you very much! I'll correct the dependency call on the next component update.

**Comment by atma** [comment]
@amireynoso Please try with v0.1.5.

**Comment by amireynoso** [comment]
@atma Will do! Thanks so much for your quick response! I'll keep you posted.
