### ISSUE TITLE
Add description to the repo

### ISSUE THREAD

**Issue by peregrinogris** [mercadolibre/tiny.js#32]
The repo currently has no description:
```
No description or website provided.
```
Maybe something like this could be used:
```
A collection of easy to use JavaScript helpers.
```

**Comment by battaglr** [comment]
@peregrinogris, nice catch! I would use the one that already exists on the readme:

> A JavaScript utility library oriented to real world tasks

@hmammana, do you have permissions to do this? Because I can't.

**Comment by battaglr** [comment]
I asked around and only the architecture team can modify this. I'll check if there are other public repos that need to add/modify its description, so they can update all at once.

**Comment by battaglr** [comment]
Closed! Thanks to @fyadon.
